### ISSUE TITLE
Make the home page add back to top button then JS functionality

### ISSUE THREAD

**Issue by norovoo** [norovoo/nelty-website#10]
When scrolling the away from the top of the website I need to create the button that head back to top of the website.

**Comment by norovoo** [comment]
Anyone who want to participate the hacktoberfest feel free to assign yourself then earn the badge.

**Comment by norovoo** [comment]
If you want to started working on this task feel free to create a new branch then create a pull request for this. Thank you

**Comment by IngaleChinmay04** [comment]
Hi, I'd like to work on this issue (Make the home page add back to top button then JS functionality). Could you please assign it to me?
