### ISSUE TITLE
Make the home page more functional

### ISSUE THREAD

**Issue by norovoo** [norovoo/nelty-website#11]
I need to create a nice banner for the home page under the menu section. Please let me know if you have any questions.

**Comment by IngaleChinmay04** [comment]
I'm interested again. What are your expectations for the banner( like what text,image, or call-to-action) would you like to include in banner?

**Comment by norovoo** [comment]
I am thinking that appropriate picture slides would be great.

**Comment by norovoo** [comment]
@IngaleChinmay04  Nice work Thank you!
