### ISSUE TITLE
Improve the UI of the Contact us page

### ISSUE THREAD

**Issue by SandhyaSankararaman** [norovoo/nelty-website#21]
![pic1](https://github.com/user-attachments/assets/1c9972d6-600b-4ca6-9717-f6416e312f2e)
![pic2](https://github.com/user-attachments/assets/d799a0df-3ba9-4f44-aadd-a3c0c541a177)
![pic3](https://github.com/user-attachments/assets/539536fd-cfba-4140-8dee-0c510f295a90)
Hi @norovoo , I would like to contribute by improving the UI of the Contact us page. I have attached an updated version for your reference. 
If it doesn't have any conflicts with your existing design, Please do assign me this issue under hacktoberfest2024.

**Comment by norovoo** [comment]
Sure. Thank you

**Comment by norovoo** [comment]
I have merged the PR. Make sure your commit message include the issue number like Closed #21.
